# Generated by Django 2.2.5 on 2021-02-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_id', models.BigIntegerField(blank=True, null=True)),
                ('run_start_date', models.DateTimeField(blank=True, null=True)),
                ('result', models.BigIntegerField(blank=True, null=True)),
                ('total_offpoint', models.BigIntegerField(blank=True, null=True)),
                ('offpoint_detail', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('comment', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ana_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryDetail',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('offpoint', models.BigIntegerField(blank=True, null=True)),
                ('evaluation_place', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OffpointDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateTimeField(blank=True, null=True)),
                ('offpoint', models.BigIntegerField(blank=True, null=True)),
                ('offpoint_category', models.BigIntegerField(blank=True, null=True)),
                ('evaluation_place', models.CharField(max_length=255,blank=True, null=True)),
                ('block_no', models.CharField(max_length=255,blank=True, null=True)),
            ],
            options={
                'db_table': 'offpoint_detail',
                'managed': False,
            },
        ),
    ]
