# Generated by Django 2.2.5 on 2021-03-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockInfoTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_cd', models.TextField(blank=True, db_column='block-cd', null=True)),
                ('block_cd_1', models.TextField(blank=True, db_column='block-cd-1', null=True)),
                ('block_cd_2', models.TextField(blank=True, db_column='block-cd-2', null=True)),
                ('block_name', models.TextField(blank=True, db_column='block-name', null=True)),
                ('block_caption', models.TextField(blank=True, db_column='block-caption', null=True)),
                ('applied_place_inside', models.BigIntegerField(blank=True, db_column='applied-place-inside', null=True)),
                ('applied_place_street', models.BigIntegerField(blank=True, db_column='applied-place-street', null=True)),
            ],
            options={
                'db_table': 'block_info_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrivingEvaluationByBlockTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_cd', models.TextField(blank=True, db_column='block-cd', null=True)),
                ('block_name', models.TextField(blank=True, db_column='block-name', null=True)),
                ('evaluation_cd', models.TextField(blank=True, db_column='evaluation-cd', null=True)),
                ('evaluation_item_name', models.TextField(blank=True, db_column='evaluation-item-name', null=True)),
            ],
            options={
                'db_table': 'driving_evaluation_by_block_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrivingEvaluationItemTbl',
            fields=[
                # ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_cd', models.TextField(blank=True, db_column='evaluation_cd', null=True)),
                ('evaluation_cd1', models.TextField(blank=True, db_column='evaluation-cd1', null=True)),
                ('evaluation_cd2', models.TextField(blank=True, db_column='evaluation-cd2', null=True)),
                ('evaluation_cd3', models.TextField(blank=True, db_column='evaluation-cd3', null=True)),
                ('evaluation_item_name', models.TextField(blank=True, db_column='evaluation-item-name', null=True)),
                ('evaluation_message', models.TextField(blank=True, db_column='evaluation-message', null=True)),
                ('score', models.BigIntegerField(blank=True, null=True)),
                ('applied_place_inside', models.BigIntegerField(blank=True, db_column='applied-place-inside', null=True)),
                ('applied_place_street', models.BigIntegerField(blank=True, db_column='applied-place-street', null=True)),
            ],
            options={
                'db_table': 'driving_evaluation_item_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.FloatField(blank=True, null=True)),
                ('driving_mode', models.TextField(blank=True, null=True)),
                ('ms_course_id', models.FloatField(blank=True, null=True)),
                ('equip_id', models.FloatField(blank=True, null=True)),
                ('driving_course_name', models.TextField(blank=True, null=True)),
                ('run_start_date', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluation_list',
                'managed': False,
            },
        ),
    ]
