# Generated by Django 2.2.5 on 2021-01-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_id', models.BigIntegerField(blank=True, null=True)),
                ('run_start_date', models.DateTimeField(blank=True, null=True)),
                ('result', models.BigIntegerField(blank=True, null=True)),
                ('total_offpoint', models.BigIntegerField(blank=True, null=True)),
                ('offpoint_detail', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('comment', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ana_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OffpointDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('measurement_date', models.DateTimeField(blank=True, null=True)),
                ('offpoint', models.BigIntegerField(blank=True, null=True)),
                ('offpoint_category', models.BigIntegerField(blank=True, null=True)),
                ('category', models.BigIntegerField(blank=True, null=True)),
                ('evaluation_place', models.BigIntegerField(blank=True, null=True)),
                ('block_no', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'offpoint_detail',
                'managed': False,
            },
        ),
    ]
