# Generated by Django 2.2.5 on 2021-03-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0002_blockinfotbl_drivingevaluationbyblocktbl_drivingevaluationitemtbl_evaluationlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DrivingEvaluationByBlockTbl',
        ),
    ]
