# Generated by Django 2.2.5 on 2021-01-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDetail',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category_detail',
                'managed': False,
            },
        ),
    ]
