# Generated by Django 2.2.5 on 2021-03-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0003_delete_drivingevaluationbyblocktbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingEvaluationByBlockTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_cd', models.TextField(blank=True, db_column='block_cd', null=True)),
                ('block_name', models.TextField(blank=True, db_column='block-name', null=True)),
                ('evaluation_cd', models.TextField(blank=True, db_column='evaluation_cd', null=True)),
                ('evaluation_item_name', models.TextField(blank=True, db_column='evaluation-item-name', null=True)),
            ],
            options={
                'db_table': 'driving_evaluation_by_block_tbl',
                'managed': False,
            },
        ),
    ]
