# Generated by Django 2.2.5 on 2021-03-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0004_drivingevaluationbyblocktbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('evaluation_cd', models.TextField(primary_key=True, serialize=False)),
                ('val1', models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True)),
                ('val2', models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True)),
                ('val3', models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True)),
                ('val4', models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True)),
            ],
            options={
                'db_table': 'threshold',
                'managed': False,
            },
        ),
    ]
